# Minhyuk Sung (mhsung@cs.stanford.edu)

#------------------------------------------------------------------------------
# Define all the global variables for the project
#------------------------------------------------------------------------------

from __future__ import division
import os, sys
BASE_DIR = os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__))))

g_synset = os.environ['synset']


# Root directory.
g_data_root_dir = os.path.join(BASE_DIR, 'data')


# Component directory.
# Pre-processed scene graph components generated by the following paper:
# Sung et al., "ComplementMe: Weakly-Supervised Component Suggestions for 3D
# Modeling", SIGGRAPH Asia 2017.
g_component_dir = os.path.abspath(os.path.join(
    g_data_root_dir, 'components', g_synset))

g_component_meshes_dir = os.path.abspath(os.path.join(
    g_data_root_dir, 'component_meshes', g_synset))

g_component_all_md5s_file = os.path.join(g_component_dir,\
        'component_all_md5s.txt')
g_component_train_md5s_file = os.path.join(g_component_dir,\
        'component_train_md5s.txt')
g_component_test_md5s_file = os.path.join(g_component_dir,\
        'component_test_md5s.txt')

g_component_all_pairs_file = os.path.join(g_component_dir,\
        'component_all_pairs.csv')
g_component_train_pairs_file = os.path.join(g_component_dir,\
        'component_train_pairs.csv')
g_component_test_pairs_file = os.path.join(g_component_dir,\
        'component_test_pairs.csv')

g_component_all_component_labels_file = os.path.join(g_component_dir,\
        'component_all_component_labels.txt')
g_component_all_centered_point_clouds_file = os.path.join(g_component_dir,\
        'component_all_centered_point_clouds.npy')
g_component_all_positions_file = os.path.join(g_component_dir,\
        'component_all_positions.npy')
g_component_all_areas_file = os.path.join(g_component_dir,\
        'component_all_areas.npy')


# Part directory.
# Semantic parts generated by the following paper:
# Yi et al., "A Scalable Active Framework for Region Annotation in 3D Shape
# Collections", SIGGRAPH Asia 2016.
g_part_dir = os.path.abspath(os.path.join(
    g_data_root_dir, 'parts', g_synset))

g_part_meshes_dir = os.path.abspath(os.path.join(
    g_data_root_dir, 'part_meshes', g_synset))

g_part_all_part_labels_file = os.path.join(g_part_dir,\
        'part_all_part_labels.txt')
g_part_all_centered_point_clouds_file = os.path.join(g_part_dir,\
        'part_all_centered_point_clouds.npy')
g_part_all_positions_file = os.path.join(g_part_dir,\
        'part_all_positions.npy')
g_part_all_areas_file = os.path.join(g_part_dir,\
        'part_all_areas.npy')


# Partial object data in test set.
# (Need to be generated by 'evaluations/generate_partial_objects.py' file.)
g_partial_dir = os.path.abspath(os.path.join(
    g_data_root_dir, 'partial_objects', g_synset))

g_partial_test_point_clouds_file = os.path.join(g_partial_dir,\
        'partial_test_point_clouds.npy')
g_partial_test_centered_point_clouds_file = os.path.join(g_partial_dir,\
        'partial_test_centered_point_clouds.npy')
g_partial_test_positions_file = os.path.join(g_partial_dir,\
        'partial_test_positions.npy')
g_partial_test_component_idxs_file = os.path.join(g_partial_dir,\
        'partial_test_component_idxs.txt')
g_partial_test_complement_idxs_file = os.path.join(g_partial_dir,\
        'partial_test_complement_idxs.txt')

